import { createClient, type SupabaseClient } from "@supabase/supabase-js";
import { createServerClient } from "@supabase/ssr";
import { cookies } from "next/headers";
import { createHash, randomBytes, randomUUID } from "node:crypto";

export type SupabaseConfig = { url: string; anonKey: string; serviceRoleKey: string };
const hash = (value: string) => createHash("sha256").update(value).digest("hex");
export function getSupabaseConfig(): SupabaseConfig { const url=process.env.NEXT_PUBLIC_SUPABASE_URL; const anonKey=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY; const serviceRoleKey=process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.SUPABASE_SECRET_KEY; if(!url) throw new Error("NEXT_PUBLIC_SUPABASE_URL is required."); if(!anonKey) throw new Error("NEXT_PUBLIC_SUPABASE_ANON_KEY is required."); if(!serviceRoleKey) throw new Error("SUPABASE_SERVICE_ROLE_KEY is required."); return {url,anonKey,serviceRoleKey}; }
export function createSupabaseAdminClient(): SupabaseClient { const config=getSupabaseConfig(); return createClient(config.url,config.serviceRoleKey,{auth:{autoRefreshToken:false,persistSession:false}}); }
export async function createDesktopTicket(ownerId:string) { const ticket=randomBytes(32).toString("base64url"); const controlSecret=randomBytes(32).toString("base64url"); const client=createSupabaseAdminClient(); const result=await client.from("desktop_pairings").insert({id:randomUUID(),owner_id:ownerId,token_hash:hash(ticket),expires_at:new Date(Date.now()+60_000).toISOString()}); if(result.error) throw new Error(result.error.message); return {ticket,controlSecret}; }
export async function exchangeDesktopTicket(ticket:string) { const client=createSupabaseAdminClient(); const pair=await client.from("desktop_pairings").select("id,owner_id,expires_at,used_at").eq("token_hash",hash(ticket)).maybeSingle(); if(pair.error || !pair.data || pair.data.used_at || new Date(pair.data.expires_at).getTime() < Date.now()) return null; const consumed=await client.from("desktop_pairings").update({used_at:new Date().toISOString()}).eq("id",pair.data.id).is("used_at",null); if(consumed.error) throw new Error(consumed.error.message); const token=`ts_${randomBytes(32).toString("base64url")}`; const session=await client.from("desktop_sessions").insert({id:randomUUID(),owner_id:pair.data.owner_id,token_hash:hash(token)}); if(session.error) throw new Error(session.error.message); return token; }
async function desktopOwner(token:string) { const client=createSupabaseAdminClient(); const result=await client.from("desktop_sessions").select("owner_id").eq("token_hash",hash(token)).is("revoked_at",null).maybeSingle(); return result.data?.owner_id ?? null; }
export async function supabaseUserId(request:Request):Promise<string|null> { const config=getSupabaseConfig(); const authorization=request.headers.get("authorization"); if(authorization?.startsWith("Bearer ")) { const token=authorization.slice(7); if(token.startsWith("ts_")) return desktopOwner(token); const client=createClient(config.url,config.anonKey,{auth:{autoRefreshToken:false,persistSession:false}}); const {data}=await client.auth.getUser(token); return data.user?.id??null; } const cookieStore=await cookies(); const client=createServerClient(config.url,config.anonKey,{cookies:{getAll:()=>cookieStore.getAll(),setAll:()=>undefined}}); const {data}=await client.auth.getUser(); return data.user?.id??null; }
